apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "user-tools-cleaner.fullname" . }}
  labels:
    {{ include "user-tools-cleaner.labels" . | nindent 4 }}
data:
  cleaner.sh: |
    #!/bin/sh
    set -exo pipefail
    tools=$(kubectl -n {{ .Release.Namespace }} get usertools.kdl.konstellation.io -o name)
    for tool in ${tools}; do
      kubectl -n {{ .Release.Namespace }} delete $tool
    done
    pvcs=$(kubectl -n {{ .Release.Namespace }} get persistentvolumeclaim  -l "app.kubernetes.io/name=user-tools" -o name)
    for pvc in ${pvcs}; do
      kubectl -n {{ .Release.Namespace }} delete $pvc
    done

