apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "user-tools-cleaner.fullname" . }}
rules:
- apiGroups:
  - kdl.konstellation.io
  resources:
  - usertools
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "user-tools-cleaner.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "user-tools-cleaner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "user-tools-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}